### ISSUE TITLE
Investigate existing Symbiota dropdown functions

### ISSUE THREAD

**Issue by Tian-Tan** [BU-Spark/se-Symbiota-portal#34]
Our client has mentioned that there is no need to create new dropdown tables and to leverage existing dropdown functions currently available in Symbiota. This requires some digging into the code to find out these existing functions.

**Comment by ttaliacc** [comment]
@Tian-Tan since the function exists, i didn't really see anywhere using this function or having dropdown list? especially not in the old entry form. I'll look around to see if there is any clue.

**Comment by ttaliacc** [comment]
Related Issues:
- #26 
- #7

**Comment by ttaliacc** [comment]
Based on the video, the field "scientific name" should have the dropdown list function. However, i didn't find related code in the occurrenceeditor.php file. So, we guess that it's because our repo is out of date. Langdon is woking on merging the new version to our repo, and we will see if we can find any potential dropdown list code.

**Comment by ttaliacc** [comment]
I took a look at the occurrenceeditor of the merge branch, but there was still nothing related to dropdown list.

**Comment by Tian-Tan** [comment]
Issue currently on hold as we approach the Symbiota devs for some pointers on the code for existing Symbiota typeahead functions

**Comment by ttaliacc** [comment]
@Tian-Tan do we still need to work on this one? Or we are good with the new dropdown function?

**Comment by Tian-Tan** [comment]
ON HOLD: Currently we need to contact Symbiota's admins to inquire about pointers to where the code for the existing dropdown functions might be. 

On the other hand, we have also implemented our own dropdown functions, but how it works is still a little different from what the client expects. There are basically 2 options here:
1. Continue trying to contact Symbiota admins and try to get the existing dropdown/typeahead functions to work.
2. Fix our already implemented dropdown functions to fit client expectations.

We should mention this in a future meeting but I'd suppose this is lower on the priority list.

**Comment by Tian-Tan** [comment]
During the meeting, Jonathan told us to let him access the dev version of the website to poke around the code himself

**Comment by ttaliacc** [comment]
The existing drop down function is using jQuery autocomplete plugin to achieve the functionality.
Here is an example(/home/herbaria/running-symbiota/js/symb/collections.editor.main.js):
<img width="500" alt="Screenshot 2024-01-27 at 2 13 36 PM" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/1f6a8df6-af6e-4585-ae25-df7a2f251152">

**Comment by ttaliacc** [comment]
For the old entry form, many autocomplete functions are broken, such as state, country.
<img width="817" alt="Screenshot 2024-02-04 at 5 39 37 PM" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/2e65e9d4-f66d-4267-9210-78af64a92183">

 I think the reason is that in our data base, we don't have state or country table, and the query fails. 

<img width="514" alt="Screenshot 2024-02-04 at 5 40 15 PM" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/07240e7c-07f5-4c6d-965a-4df8f610f8ff">

Should we fix it? and how?

**Comment by ttaliacc** [comment]
Finish implementing one of the dropdown. Should i move on to implement all field's drop?

**Comment by ttaliacc** [comment]
Implemented all dropdowns with commit 001ca652fefe51f4944f96daefc25aafb5e0d6cd
